version: '3'

# assign a new common network and attach all services to it.
networks:
    app_network:
        name: app_network

services:
  postgres:
    image: postgres:latest
    container_name: invoices-dwh
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.00'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ".env.sh"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestor:
    container_name: ingestor
    build:
        context: .
    networks:
      - app_network
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ".env.sh"
    command: bash -c "echo 'inside data_ingestor container.'  &&  python3 entry_point.py"
    # command: ["bin/wait_for_postgres.sh", "bash", "python3", "app.py"]

  dashboard:
    image: metabase/metabase
    container_name: dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    depends_on:
      - ingestor
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - app_network

volumes:
    postgres_data: